### ISSUE TITLE
NetStatus for RPi - "xset unable to open display"

### ISSUE THREAD

**Issue by spickles** [Ryandev/NetStatus#3]
Followed all of the instructions for the RPi installation and get the error "xset unable to open display".  Please advise.

**Comment by Ryandev** [comment]
That issue looks related to being unable to see the display. It sounds like it happens when run via ssh. You could try running it from a gui terminal on the pi itself otherwise according to https://askubuntu.com/questions/476036/xset-unable-to-open-display
calling `export DISPLAY=:0` before calling `xset` should fix your issue

**Comment by spickles** [comment]
Thanks Ryan.  We stumbled upon that somewhere on the 'net and the export allows the script to continue.  We're not sure, though, where to set that and make it persistent.  We are running Raspbian as opposed to Ubuntu, but not sure that really matters?  I added `export DISPLAY=:0` to `/etc/environment` but it still doesn't launch on start.  I may need to do something else to launch the `browser.sh` script since we're on Raspbian.

**Comment by Ryandev** [comment]
Ok, sorry it was late, However `export DISPLAY=:0` wont be needed as it will be running from the device locally not from ssh. I assume the script is also firing on boot & not manually via ssh

So it looks like theirs issues with the latest raspbian `xset` (Ref.1). You could try running `sudo raspi-config` & set blanking to disabled (Ref.2) or try editing `~/.config/lxsession/LXDE-pi/autostart` with
```
@xset s off
@xset -dpms 
@xset s noblank
``` (Ref.1)

Ref.1 `https://www.geeks3d.com/hacklab/20160108/how-to-disable-the-blank-screen-on-raspberry-pi-raspbian/`

It's untested in all other distros, let me know how you get on & I'll update the instructions

**Comment by spickles** [comment]
No worries.  We were maximizing our options by reaching out to you here as well as Google.  We are going to switch over to Ubuntu to be sure we can get it up and running with your instructions and then perhaps try Raspbian.

**Comment by Ryandev** [comment]
There should be nothing wrong with using Raspian as its still a debian distro. I just haven’t tested it.

All the commands are documented & you can always use google to find alternatives.

If you’re still struggling & are considering reflashing, balena support has been added (not by myself)

**Comment by spickles** [comment]
Meaning Balena will flash an SD card with a working image of all of this
already put together?

**Comment by Ryandev** [comment]
Balena is a way of managing docker-images/software running on your Pi from their website. You flash the sd-card with a balena image & it then connects to your account (Not something I've tested, however at least a few people have had success with this)
