### ISSUE TITLE
wrong Upload speed

### ISSUE THREAD

**Issue by HappyPlaceGA** [Ryandev/NetStatus#5]
Using link https://netstatus.ryanpowell.dev/dashboard on my pc.
My ISP provides 50 down/10 up
Speedtest.net shows 48 down/10 up

Your link shows: 52 down /232 up which is impossible.
Something is clearly wrong with upload speed measuring.
![Capture](https://user-images.githubusercontent.com/52013674/111183066-e68bd380-8585-11eb-9936-e6335ae0bb35.PNG)

**Comment by Ryandev** [comment]
Hi,

Thanks for raising this. Yes, this is clearly an issue. I assume this happens across multiple devices in your household when visiting:  https://netstatus.ryanpowell.dev/dashboard?

Does this consistently happen? Is it always incorrect? (When you tap to refresh) Does the results change?

If the above is true, can you run a speed test from this website: [https://librespeed.org](https://librespeed.org) Are you seeing the same upload speed issue?

**Comment by Ryandev** [comment]
Cannot progress without feedback. Closing issue. 

Please re-open once feedback has been added
