### ISSUE TITLE
Raspberry PI Instructions

### ISSUE THREAD

**Issue by TurboKia** [Ryandev/NetStatus#6]
Sorry, only way I see to get a response.  Tried following your PI instructions to the T, and nothing works.   I have a Pi 4 and the 3.5 in display, but nothing shows up but a white screen.  Tried the Belena approach, and it's showing up on the dash board, but nothing on the screen.  I can get Ubuntu up and running and it shows, resolution is off, but it does work ...

I guess what I'm looking for are some clearer instructions, something for a semi noob.  I'm using putty to do everything., and following this direction:
https://github.com/Ryandev/NetStatus/blob/master/documentation/rpi.md

I get lost after step 4. For example, first line is 
echo 'Disabling screensaver' &&
gsettings set org.gnome.desktop.screensaver lock-enabled false.

They only thing i see that needs to be done is:  gsettings set org.gnome.desktop.screensaver lock-enabled false

Again, I'm using putty ... is this supposed to be run in a terminal window under Ubuntu?

Anyway, any help would be appreciated ... email address is gsgamble@outlook.com

Thanks,
Greg Gamble
Washington, USA

**Comment by Ryandev** [comment]
I'm sorry to hear that. I can't speak to Balena, however there's atleast 2 individiuals who have tested it working sucessfully there.

Yes, that is correct for 'step 4'. The echo is just for documentation purposes, so you can see why we are making each change & if you can't get any step to work, you at least know what to search for online.

As for the commands, yes thats fine, to run it remotely through ssh/putty.

* Which image did you start with? Ubuntu or Raspian? 
*  How far through the instructions did you get? Did you complete all the steps?

Best Regards,
Ryan Powell

**Comment by Ryandev** [comment]
Cannot progress without feedback. Closing issue. 

Please re-open once feedback has been added

**Comment by TurboKia** [comment]
Wow, some how I missed your reply .... sorry about that.
I created one using flask, that runs in a browser fine, But can't get it working in kiosk mode, as I need to run a flask py file first ... work in progress I guess

I tried using Ubuntu, but will try in Raspian too.  I'll get back with more details, but if others are doing it, it's got to be me doing something wrong ... will try again.

**Comment by TurboKia** [comment]
Raspbian is a no ... gsettings not available.

This should work on Ubuntu 20.04.2 LTS, right?  Trying on the 32bit version.

**Comment by TurboKia** [comment]
OK ... did it twice, and it just loads the ubuntu desktop.  I login and nothing. just a blank desktop.

**Comment by Ryandev** [comment]
So there's 2 parts to the software running (1. The webserver that runs the NetStatus, 2. The browser which runs fullscreen & points to #1)

If you're getting a blank screen, you may be having issues with #1 not running. You may need to check Docker is running.

Flask Py, is a web framework & shouldn't be necessary here.

I'm not familiar with your skill level, however if you're finding this task challenging. I think the Balena route may provide an easier path. There's instructions on the readme & a 'Deploy with Balena' button

If I get a chance. I'll see if I can setup some more detailed instructions, or video. However it may be a while.

**Comment by TurboKia** [comment]
The flask PY was for a separate project I used to mimic this one.  I'm getting a Ubuntu desktop, which I can login to fine.  I'll verify docker is setup correctly.

A video would be awesome.  As for experience.  I'm a web programmer, using c#.  Been doing that for about 14 years.  I have some LAMP experience to.  Docker is new to me though, so I'll see if I can find anything messed up.

I can run it by entering the IP, so the net status part is working.

4/14 Update:
==============================================================================
If I open Chromium on the Pi, after logging in, I can go to localhost and it works., so it has to be a setting on the autostart.  Working on it.

Also, is there a way to set the server to test on?  I'm in the US, and wanting to point to Comcast here in the US.  I'm thinking that why the latency is so high and the download speeds are so low.
